version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "./docker-entrypoint.sh dotnet Dfe.PrepareTransfers.Web.dll"
    ports:
      - 80:80/tcp
    env_file:
      - .env.development
    networks:
      - dev

networks:
  dev: