version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.gpaas-azure-migration
    command: /bin/bash -c "./docker-entrypoint.sh dotnet Dfe.PrepareTransfers.Web.dll"
    ports:
      - 80:80/tcp
    env_file:
      - .env.development
    depends_on:
      - redis
    networks:
      - dev

  redis:
    image: redis:6
    ports:
      - 6379:6379
    networks:
      - dev

networks:
  dev: