namespace Data.TRAMS.Models
{
    public class TramsEstablishment
    {
        public Address Address { get; set; }
        public NameAndCode AdministrativeWard { get; set; }
        public NameAndCode AdmissionsPolicy { get; set; }
        public NameAndCode Boarders { get; set; }
        public string BoardingEstablishment { get; set; }
        public string Ccf { get; set; }
        public Census Census { get; set; }
        public string CensusAreaStatisticWard { get; set; }
        public string CloseDate { get; set; }
        public Placeholder Concerns { get; set; }
        public string Country { get; set; }
        public string DateOfLastInspectionVisit { get; set; }
        public string DateOfNextInspectionVisit { get; set; }
        public NameAndCode Diocese { get; set; }
        public NameAndCode DistrictAdministrative { get; set; }
        public string Easting { get; set; }
        public string Ebd { get; set; }
        public string EdByOther { get; set; }
        public string EstablishmentName { get; set; }
        public string EstablishmentNumber { get; set; }
        public NameAndCode EstablishmentStatus { get; set; }
        public NameAndCode EstablishmentType { get; set; }
        public string EstablishmentTypeGroupCode { get; set; }
        public string FederationFlag { get; set; }
        public NameAndCode Federations { get; set; }
        public string FeheiIdentifier { get; set; }
        public Placeholder Financial { get; set; }
        public string FtProv { get; set; }
        public string FurtherEducationType { get; set; }
        public NameAndCode Gender { get; set; }
        public NameAndCode Gor { get; set; }
        public string GsslaCode { get; set; }
        public string HeadteacherFirstName { get; set; }
        public string HeadteacherLastName { get; set; }
        public string HeadteacherPreferredJobTitle { get; set; }
        public string HeadteacherTitle { get; set; }
        public string Inspectorate { get; set; }
        public string InspectorateName { get; set; }
        public string InspectorateReport { get; set; }
        public string LastChangedDate { get; set; }
        public string LocalAuthorityCode { get; set; }
        public string LocalAuthorityName { get; set; }
        public NameAndCode Lsoa { get; set; }
        public MisEstablishment MisEstablishment { get; set; }
        public Misfea MisFurtherEducationEstablishment { get; set; }
        public NameAndCode Msoa { get; set; }
        public string Northing { get; set; }
        public string NurseryProvision { get; set; }
        public NameAndCode OfficialSixthForm { get; set; }
        public string OfstedLastInspection { get; set; }
        public string OfstedRating { get; set; }
        public NameAndCode OfstedSpecialMeasures { get; set; }
        public string OpenDate { get; set; }
        public NameAndCode ParliamentaryConstituency { get; set; }
        public NameAndCode PhaseOfEducation { get; set; }
        public string PlacesPru { get; set; }
        public string PreviousEstablishmentNumber { get; set; }
        public NameAndCode PreviousLocalAuthority { get; set; }
        public string PropsName { get; set; }
        public NameAndCode ReasonEstablishmentClosed { get; set; }
        public NameAndCode ReasonEstablishmentOpened { get; set; }
        public NameAndCode ReligiousCharacter { get; set; }
        public string ReligiousEthos { get; set; }
        public string ResourcedProvisionOnCapacity { get; set; }
        public string ResourcedProvisionOnRoll { get; set; }
        public string RscRegion { get; set; }
        public string SchoolCapacity { get; set; }
        public string SchoolSponsorFlag { get; set; }
        public string SchoolSponsors { get; set; }
        public string SchoolWebsite { get; set; }
        public string Section14Approved { get; set; }
        public string Sen1 { get; set; }
        public string Sen10 { get; set; }
        public string Sen11 { get; set; }
        public string Sen12 { get; set; }
        public string Sen13 { get; set; }
        public string Sen2 { get; set; }
        public string Sen3 { get; set; }
        public string Sen4 { get; set; }
        public string Sen5 { get; set; }
        public string Sen6 { get; set; }
        public string Sen7 { get; set; }
        public string Sen8 { get; set; }
        public string Sen9 { get; set; }
        public string SenNoStat { get; set; }
        public string Senpru { get; set; }
        public string SenStat { get; set; }
        public string SenUnitCapacity { get; set; }
        public string SenUnitOnRoll { get; set; }
        public SmartData SmartData { get; set; }
        public NameAndCode SpecialClasses { get; set; }
        public string StatutoryHighAge { get; set; }
        public string StatutoryLowAge { get; set; }
        public string TeenMoth { get; set; }
        public string TeenMothPlaces { get; set; }
        public string TelephoneNumber { get; set; }
        public NameAndCode Trusts { get; set; }
        public NameAndCode TrustSchoolFlag { get; set; }
        public string TypeOfResourcedProvision { get; set; }
        public string Ukprn { get; set; }
        public string Uprn { get; set; }
        public NameAndCode UrbanRural { get; set; }
        public string Urn { get; set; }
    }
}