---
applications:
- name: academy-transfers-production
  buildpacks:
    - dotnet_core_buildpack
  env:
    "AAD:Instance": ((aad_instance))
    "AAD:ResourceId": ((aad_resource_id))
    "AAD:TenantId": ((aad_tenant_id))
    username: ((username))
    password: ((password))
