name: .NET

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    # This could be cached in the future to allow for quicker build times
    - name: Build Frontend
      run: make build-frontend
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Cypress tests
      uses: cypress-io/github-action@v2
      with:
        build: npm run build
        start: npm start
