name: Cypress test linting

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
    paths:
      - end-to-end-tests/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: lint cypress tests
        run: |
          cd end-to-end-tests
          npm ci
          npm run lint        
