name: Deploy to staging

on:
  workflow_dispatch:

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      # This could be cached in the future to allow for quicker build times
      - name: Build Frontend
        run: make build-frontend
      - name: Install CloudFoundry CLI
        shell: bash
        id: install-cf-cli
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli

      - name: Deploy Code
        run: |
          cf api https://api.london.cloud.service.gov.uk
          cf auth "${{ secrets.CF_USER }}" "${{ secrets.CF_PASSWORD }}"
          cf target -o dfe -s academy-transfers-staging
          cf push amsd-casework-staging --docker-image ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:latest -f deploy-manifests/staging.yml \
          --strategy rolling \
          --var username=${{ secrets.USERNAME }} \
          --var password=${{ secrets.PASSWORD }} 
