name: Docker build

on:
  pull_request:
    paths:
      - Dockerfile
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          secrets: github_token=${{ secrets.GITHUB_TOKEN }}
          push: false
