name: End to end tests

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: dfe-digital/academy-transfers-api

jobs:
  run_tests:
    permissions:
      contents: read
      packages: read

    runs-on: ubuntu-latest
    environment: Dev
    defaults:
      run:
        working-directory: end-to-end-tests

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      
      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Npm install
        run: npm install
      
      - name: Verify logs
        run: docker logs "${{ job.services.web-app.id }}"

      - name: Run tests
        run: npm run cypress:run -- --record --key ${{ secrets.CYPRESS_KEY }} --env username='${{ secrets.USERNAME }}',password='${{ secrets.PASSWORD }}',url='${{ secrets.ENDPOINT }}'
  
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: end-to-end-tests/cypress/screenshots
