name: End to end tests

on:
  workflow_run:
    workflows: [ "Test, build, and deploy" ]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: dfe-digital/academy-transfers-api

jobs:
  run_tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: read

    runs-on: ubuntu-latest
    environment: Dev
    defaults:
      run:
        working-directory: end-to-end-tests

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Npm install
        run: npm install
      
      #      - name: Verify logs
      #        run: docker logs "${{ job.services.web-app.id }}"

      - name: Run tests
        run: npm run cypress:run -- --record --key ${{ secrets.CYPRESS_KEY }} --env url='${{ secrets.ENDPOINT }}',authorizationHeader='${{ secrets.AUTH_HEADER_CYPRESS }}'

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: end-to-end-tests/cypress/screenshots

    cypress-tests:
    needs: deploy-image
    environment: staging
    if: ${{ github.event.inputs.environment}} == staging
    runs-on: ubuntu-22.04
    defaults:
      run:
         working-directory: end-to-end-tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Npm install
        run: npm install
      - name: Run cypress
        run: npm run cy:run -- --env url='${{ secrets.ENDPOINT }}',authorizationHeader='${{ secrets.CYPRESS_TEST_SECRET }}'
        env:
          db: ${{ secrets.DB_CONNECTION_STRING }}
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
         name: screenshots
         path: end-to-end-tests/cypress/screenshots        
