name: End to end tests

on:
  workflow_run:
    workflows: [ "Test, build, and deploy", "Deploy to environment" ]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: dfe-digital/academy-transfers-api

jobs:
  run_tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.conclusion.inputs.environment != 'production' }}
    permissions:
      contents: read
      packages: read

    runs-on: ubuntu-latest
    environment: ${{ github.event.workflow_run.conclusion.inputs.environment == 'staging' && 'Staging' || 'Dev' }}
    defaults:
      run:
        working-directory: end-to-end-tests

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Npm install
        run: npm install
      
      #      - name: Verify logs
      #        run: docker logs "${{ job.services.web-app.id }}"
      - name: debug1
        run: echo LAST_RUN_ENV - ${{ github.event.workflow_run.conclusion.inputs.environment }}

      - name: debug2
        run: echo ENV_TERNARY - ${{ github.event.workflow_run.conclusion.inputs.environment == 'staging' && 'Staging' || 'Dev' }}

      - name: Run tests
        run: npm run cypress:run -- --key ${{ secrets.CYPRESS_KEY }} --env url='${{ secrets.ENDPOINT }}',authorizationHeader='${{ secrets.AUTH_HEADER_CYPRESS }}'

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: end-to-end-tests/cypress/screenshots
